### PR TITLE
Move results table to BoneJCommand

### PR DESCRIPTION
**Pull request by rimadoma**
Contrary to what I claimed in #245 it's possible to move the results table to the base class. The failing tests mentioned failed because one of our commands didn't call its results table `resultsTable`.

### CODE REVIEW

**Comment by rimadoma** [comment]
@alessandrofelder If you have the time, can you help to check that EF still works as intended, please?

**Comment by alessandrofelder** [comment]
No problems with EF as far as I can tell. Changes to code looks good to me as well.

**Comment by mdoube** [comment]
@rimadoma please handle the conflicts and do the merge

**Comment by rimadoma** [comment]
> @rimadoma please handle the conflicts and do the merge

Sorted

**Pull request merged**
