### PR TITLE
Switch from ImageJ Jenkins to Travis CI

### PR DESCRIPTION
**Pull request by ctrueden**
__Please do not merge yet.__

To make this work, first visit https://travis-ci.org/bonej-org/BoneJ2 and enable the repository. Once that is done, I can amend the final commit to include the encrypted credentials, and then this PR will be ready to go. Unfortunately, the Travis CLI tool will not generate the tokens until after the repository has been enabled.

Once this PR is merged, we can delete the [old Jenkins job](http://jenkins.imagej.net/view/BoneJ/).

### CODE REVIEW

**Comment by rimadoma** [comment]
Thank you very much for the help! I will attend to this PR soon.

**Comment by ctrueden** [comment]
@rimadoma I have rebased this PR over the latest master. We should merge soon to avoid further conflicts in future. All you need to do is enable Travis for the repository as described above—should take only a couple of minutes to do—and then I can add the encrypted credentials and the branch will be ready to go.

**Comment by ctrueden** [comment]
@rimadoma Could you please enable Travis CI for this repository, so that we can finalize this PR? Thank you!

**Comment by ctrueden** [comment]
Updated, and rebased over latest master. The Travis config has been updated to the latest approach we developed at the recent hackathon. The build script now delegates to a [dedicated external build script](https://github.com/scijava/scijava-scripts/blob/f5965c360cae34c3f879f8e01c2382cea5ae16de/travis-build.sh), to minimize the need for future changes to individual repositories relating to Travis builds.

**Comment by rimadoma** [comment]
Apologies for my extreme tardiness. How is the Travis build set up? For the moment I would *not* like the Legacy module to be built with the Modern one. We feel mixing the two would be too confusing, but the old code hangs around as a fall-back in case there isn't enough time to complete the ImageJ2 plugins.

**Comment by ctrueden** [comment]
> For the moment I would not like the Legacy module to be built with the Modern one.

From a technical standpoint, we can certainly disable the build of the modules in the Legacy subtree. Just remove `<module>Legacy</module>` from the top-level POM. And if you want to make it optional, you can add a profile with `<id>legacy</id>` that reintroduces it, and do a build including it with `mvn -Plegacy`. I can add a commit that makes these changes to this PR.

However, I would discourage you from doing that, because one critical purpose of CI is to test your builds. If you don't build the legacy code via Travis, then you won't know when the Legacy components have breakages in the code.

> We feel mixing the two would be too confusing

I am curious what you mean. Who would be confused? And by what? Is it that you don't want to _deploy_ the legacy components by default? If so, we could add a configuration flag, off by default, which controls deployment of that subtree separately. Would that satisfy you?

**Comment by rimadoma** [comment]
> because one critical purpose of CI is to test your builds

That's a fair point. Development in _Modern_ shouldn't affect _Legacy_, but never say never.

> Who would be confused? And by what?

The users by the different look and feel of the IJ1 v. IJ2 plug-ins. It'd be difficult for them to conceive what's part of BoneJ and what's not.

>  Would that satisfy you?

That'd be cracking.

**Comment by rimadoma** [comment]
Sorry I read your detailed instructions poorly. I'll let you know as soon as I've got the Travis repository enabled.

**Comment by rimadoma** [comment]
Updating to `pom-scijava 17.1.1` breaks the build. First, `org.scijava.util` is not found, and then Maven crashes with:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (enforce-rules) on project utilities: Execution enforce-rules of goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (enforce-rules) on project utilities: Execution enforce-rules of goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution enforce-rules of goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at org.apache.maven.plugins.enforcer.EnforceBytecodeVersion.isBadArtifact(EnforceBytecodeVersion.java:311)
	at org.apache.maven.plugins.enforcer.EnforceBytecodeVersion.checkDependencies(EnforceBytecodeVersion.java:220)
	at org.apache.maven.plugins.enforcer.EnforceBytecodeVersion.handleArtifacts(EnforceBytecodeVersion.java:146)
	at org.apache.maven.plugins.enforcer.AbstractResolveDependencies.execute(AbstractResolveDependencies.java:77)
	at org.apache.maven.plugins.enforcer.EnforceMojo.execute(EnforceMojo.java:193)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more

```

**Comment by rimadoma** [comment]
Had problems with the build, but Fixed in `master` by specifying `scijava-common` version in POMs. Is this related to the [Maven BOM change](http://forum.imagej.net/t/maven-3-4-0-may-break-imagej-and-fiji-project-builds/2471)?

**Comment by rimadoma** [comment]
I discovered I need BoneJ organization credentials for that. I'm not marked as owner, so I'm waiting for @mdoube to grant those rights to Travis CI.

**Comment by mdoube** [comment]
Approved just now.

**Comment by ctrueden** [comment]
I tried again to generate the encrypted variable for bonej-org/BoneJ2, but I still receive the error:
```
repository not known to https://api.travis-ci.org/: bonej-org/BoneJ2
```
Perhaps one of you could click the button to force a resync? Or if not, I'll try again tomorrow.

**Comment by mdoube** [comment]
Try again, I clicked some more activate buttons in different places

**Comment by ctrueden** [comment]
@mdoube Great, it worked now. See #66.

**Pull request merged**
