### PR TITLE
Update scijava to 30.0.0

### PR DESCRIPTION
**Pull request by mdoube**

### CODE REVIEW

**Comment by mdoube** [comment]
Addresses #282

**Review by rgaiacs — APPROVED** [review]
Looks good to me.

**Review by alessandrofelder — APPROVED** [review]
Is it because @rgaiacs is not on the [BoneJ2 refactoring team ](https://github.com/orgs/bonej-org/teams/bonej2) that his approval is not sufficient for merging?
Somehow he should get write access (don't think I can add him as I am a member, not an owner of the BoneJ Org)?

I assume this has been tested locally with `mvn test -P allTests`, right? Just in case SciJava 30 breaks some API that we only use in the wrappers?

If so, happy with the changes too.

**Comment by mdoube** [comment]
> I assume this has been tested locally with `mvn test -P allTests`, right? Just in case SciJava 30 breaks some API that we only use in the wrappers?

Assumuption is the mother of all eff-ups... need to fix these tests prior to merging. These failures are reminiscent of something we've dealt with before.

```
[ERROR] Tests run: 18, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 0.978 s <<< FAILURE! - in org.bonej.wrapperPlugins.AnalyseSkeletonWrapperTest
[ERROR] testIntensityImageChannelsCancelPlugin(org.bonej.wrapperPlugins.AnalyseSkeletonWrapperTest)  Time elapsed: 0.043 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[The intensity image can't have a channel dimension]> but was:<[An error occurred while opening the image]>
	at org.bonej.wrapperPlugins.AnalyseSkeletonWrapperTest.testIntensityImageChannelsCancelPlugin(AnalyseSkeletonWrapperTest.java:188)

[ERROR] testIntensityImageFramesCancelPlugin(org.bonej.wrapperPlugins.AnalyseSkeletonWrapperTest)  Time elapsed: 0.024 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[The intensity image can't have a time dimension]> but was:<[An error occurred while opening the image]>
	at org.bonej.wrapperPlugins.AnalyseSkeletonWrapperTest.testIntensityImageFramesCancelPlugin(AnalyseSkeletonWrapperTest.java:206)

[ERROR] testIntensityImageMismatchingDimensionsCancelPlugin(org.bonej.wrapperPlugins.AnalyseSkeletonWrapperTest)  Time elapsed: 0.035 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[The intensity image should match the dimensionality of the input] image> but was:<[An error occurred while opening the] image>
	at org.bonej.wrapperPlugins.AnalyseSkeletonWrapperTest.testIntensityImageMismatchingDimensionsCancelPlugin(AnalyseSkeletonWrapperTest.java:226)

[ERROR] testNot8BitIntensityImageCancelsPlugin(org.bonej.wrapperPlugins.AnalyseSkeletonWrapperTest)  Time elapsed: 0.018 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[The intensity image needs to be 8-bit greyscal]e> but was:<[An error occurred while opening the imag]e>
	at org.bonej.wrapperPlugins.AnalyseSkeletonWrapperTest.testNot8BitIntensityImageCancelsPlugin(AnalyseSkeletonWrapperTest.java:293)

```

**Comment by mdoube** [comment]
Failing tests in `AnalyseSkeletonWrapperTests` have one thing in common, which is:
```java
// in some method above
{
    final String intensityPath ="8bit-signed&pixelType=int8&planarDims=2&lengths=5,5,3&axes=X,Y,Channel.fake";
    mockIntensityFileOpening(intensityPath);
}

private void mockIntensityFileOpening(final String path) {
	final File intensityFile = mock(File.class);
	when(intensityFile.getAbsolutePath()).thenReturn(path);
	when(MOCK_UI.chooseFile(any(File.class), anyString())).thenReturn(intensityFile);
}
```
So it seems like a problem with the mocking of the broken file.

**Review by alessandrofelder — APPROVED** [review]

**Comment by mdoube** [comment]
Also see #273

**Pull request merged**
