### PR TITLE
Usage

### PR DESCRIPTION
**Pull request by mdoube**
Adds usage reporting to EF2.

### CODE REVIEW

**Comment by mdoube** [comment]
`EllipsoidFactorWrapper` usage reporting needs a test, as per the other `Wrappers`. I had a go by copying the pattern in the other `WrapperTests` but am missing some secret sauce. @rimadoma, please help.

**Comment by rimadoma** [comment]
@alessandrofelder Can you help with `EllipsoidFactorWrapperTest.testSuccessfulRunReports`? What kind of test image would run successfully?

**Comment by mdoube** [comment]
> What kind of test image would run successfully?

I see that there is a test image maker for EF:
https://github.com/bonej-org/BoneJ2/blob/master/Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/CreateEFTestImage.java

It should probably move elsewhere. Is there already a section for test image creation that tests can call?

**Comment by alessandrofelder** [comment]
Hi both,

Yes, I would expect EF to run successfully on any of the images created by the code that @mdoube refers to (I had forgotten that exists!) - agree it should move elsewhere, it is reasonably EF-specific although could be used for other purposes, I guess.

A very simple image that EF should run well on would be a binary of a sphere with say radius 5, I would say. Something like https://github.com/bonej-org/BoneJ2/blob/228fe0afa7c36a4e5a875f665659fe8081a1237d/Modern/ops/src/test/java/org/bonej/ops/ellipsoid/EllipsoidOptimisationStrategyTest.java#L51 that returns an ImgPlus instead of a byte array.

**Comment by rimadoma** [comment]
I think I've managed to write the tests now, @alessandrofelder if you wouldn't mind checking they make sense. @mdoube There's no general `CreateTestImages` utility class, each test class is creating its own.

**Comment by mdoube** [comment]
> There's no general `CreateTestImages` utility class

Maybe we should make one. BoneJ1 had one I think. Some images can be reused in multiple tests, e.g. the binary noise image should have a volume fraction of 0.5 and DA of 0.

**Comment by mdoube** [comment]
> I messed up with rebasing

...you wouldn't be the first! Easily done. I'm doing something like this now, when I come to work on a branch:
```
git checkout some-branch
git fetch origin
git rebase origin/some-branch
<do work and commit changes locally usually via the IDE>
git push origin some-branch
```
I took your advice and switched to having `bonej-org/BoneJ2` as my origin. The new GitHub squash and merge button does a good job of tidying up all the little commits on the development branch into one commit representing the merge from the PR.

**Comment by alessandrofelder** [comment]
`mvn clean package -PallTests` causes a NullPointerException to be thrown from the EF wrapper test's ` testCancelledRunDoesNotReport` on my machine, but the test passes when run individually - will investigate now :)

**Comment by rimadoma** [comment]
> I haven't seen this before (although wasn't looking as closely), and it doesn't make sense conceptually or with the constraint >1 we are trying to impose. Thoughts?

I've seen this before. Some times when I launch Anisotropy the dialog opens with "directions 1, lines per direction 1" even thought that shouldn't happen. I think this is because the command has been run programmatically, and those values have been saved to prefs. Anyhow, this is a question we should ask on the forum.

**Comment by rimadoma** [comment]
> `mvn clean package -PallTests` causes a NullPointerException to be thrown from the EF wrapper test's ` testCancelledRunDoesNotReport` on my machine, but the test passes when run individually

Can't reproduce this particular one either, but again the wrapper tests were being a bit finicky. Trying something in 226076e. Like I've said before, I can only see these random test failures when tests run from Maven, not from IDE.

**Comment by rimadoma** [comment]
@alessandrofelder I did some investigation, and "min" has no effect on running a command programmatically. That is, running

```
    @Parameter(min = "1")
    private int positiveNumber = 1;
    
    @Override
    public void run() {
        System.out.println("My number is " + positiveNumber);
    }

    public static void main(final String[] args) throws ExecutionException, InterruptedException {
        final ImageJ imageJ = new ImageJ();
        imageJ.command().run(MyCommand.class, true, "positiveNumber", -1).get();
    }
```
Prints `My number is -1`

What's more, if you set `required = false` for `positiveNumber`, and then run the command again without the parameter, the number is still `-1` because it persists... -_-

**Comment by mdoube** [comment]
> I think I've managed to write the tests now, @alessandrofelder if you wouldn't mind checking they make sense.

`mvn -P allTests` fails with:
```
[INFO] Running org.bonej.wrapperPlugins.EllipsoidFactorWrapperTest
[ERROR] Module threw exception
java.lang.NullPointerException
	at org.bonej.wrapperPlugins.EllipsoidFactorWrapper.getSkeletonPoints(EllipsoidFactorWrapper.java:471)
	at org.bonej.wrapperPlugins.EllipsoidFactorWrapper.runEllipsoidOptimisation(EllipsoidFactorWrapper.java:426)
	at org.bonej.wrapperPlugins.EllipsoidFactorWrapper.run(EllipsoidFactorWrapper.java:218)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] Found 0 ellipsoids in 19 ms
[ERROR] Tests run: 6, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 0.601 s <<< FAILURE! - in org.bonej.wrapperPlugins.EllipsoidFactorWrapperTest
[ERROR] testCancelledRunDoesNotReport(org.bonej.wrapperPlugins.EllipsoidFactorWrapperTest)  Time elapsed: 0.088 s  <<< ERROR!
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at org.bonej.wrapperPlugins.EllipsoidFactorWrapperTest.testCancelledRunDoesNotReport(EllipsoidFactorWrapperTest.java:65)
Caused by: java.lang.NullPointerException

[ERROR] testSuccessfulRunReports(org.bonej.wrapperPlugins.EllipsoidFactorWrapperTest)  Time elapsed: 0.12 s  <<< FAILURE!
java.lang.AssertionError: Sanity check failed: method cancelled
	at org.bonej.wrapperPlugins.EllipsoidFactorWrapperTest.testSuccessfulRunReports(EllipsoidFactorWrapperTest.java:87)
```

**Comment by alessandrofelder** [comment]
@mdoube this is what I got the first time I ran it - can you reproduce a second time?

**Comment by mdoube** [comment]
> can you reproduce a second time?

Yes, and on a different machine.

**Comment by alessandrofelder** [comment]
I think it's something weird with the default input parameters... maybe these need to be specified more explicitly. Will try to write a fix now.

**Comment by alessandrofelder** [comment]
@mdoube can you check whether the latest commit fixes this?
Have run `mvn clean package -PallTests` 3 times on my machine, and all tests passed each time (apart from the AnalyzeSkeletonWrapper tests timing out once).

**Comment by mdoube** [comment]
@alessandrofelder I still get this:
```
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.514 s <<< FAILURE! - in org.bonej.wrapperPlugins.EllipsoidFactorWrapperTest
[ERROR] testSuccessfulRunReports(org.bonej.wrapperPlugins.EllipsoidFactorWrapperTest)  Time elapsed: 0.1 s  <<< FAILURE!
java.lang.AssertionError: Sanity check failed: method cancelled
	at org.bonej.wrapperPlugins.EllipsoidFactorWrapperTest.testSuccessfulRunReports(EllipsoidFactorWrapperTest.java:87)
```

**Comment by alessandrofelder** [comment]
Argh! Sorry! Can try to have another go after work today!

**Comment by mdoube** [comment]
Merging `master` back in breaks  `mvn clean package`
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project bonej-plugins: Compilation failure
[ERROR] /home/mdoube/git/pom-bonej/Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/EllipsoidFactorWrapper.java:[306,84] cannot find symbol
[ERROR] symbol:   variable commandService
[ERROR] location: class org.bonej.wrapperPlugins.EllipsoidFactorWrapper
[ERROR] -> [Help 1]
```

**Comment by rimadoma** [comment]
> Merging `master` back in breaks `mvn clean package`

Fixed in rebase

**Comment by rimadoma** [comment]
@alessandrofelder @mdoube Do the tests work for you now? I set all the parameters exactly as they are on my laptop.

**Comment by mdoube** [comment]
> Do the tests work for you now?

Yes, for EF2. I get an `[INFO]` though:
```
[INFO] /home/mdoube/git/pom-bonej/Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/EllipsoidFactorWrapper.java: /home/mdoube/git/pom-bonej/Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/EllipsoidFactorWrapper.java uses unchecked or unsafe operations.
[INFO] /home/mdoube/git/pom-bonej/Modern/wrapperPlugins/src/main/java/org/bonej/wrapperPlugins/EllipsoidFactorWrapper.java: Recompile with -Xlint:unchecked for details.
```
(Also that pesky fractal dimension is still throwing an error: is it possible that it's looking up the wrong row or column in the table?)

**Comment by rimadoma** [comment]
> Yes, for EF2. I get an [INFO] though:

I reckon that's all the raw types / unchecked casts in. I had a quick go at trying to fix those earlier, but it involves changing quite a lot of stuff. I'm nervous about breaking stuff (runtime ClassCastExceptions etc), because I don't know EF that well.

**Comment by rimadoma** [comment]
> (Also that pesky fractal dimension is still throwing an error: is it possible that it's looking up the wrong row or column in the table?)

I can't repeat this, and those tests haven't really changed at least since 2018. The Fractal dimension ops (BoxCount, Outline) have changed though,  when I optimised them a while ago. I remember @ctrueden reporting that tests were failing on a specific laptop, but not in other environments.

@mdoube I'll try something and send you a `imagej-ops-SNAPSHOT`

**Comment by rimadoma** [comment]
@mdoube Solving merge conflicts with updated `master` required a good bit of fiddling. Do you mind checking again that this PR is still OK on your end please?

**Comment by rimadoma** [comment]
@mdoube Can you also make a note of the exact combination of values that caused the tests crash? That'd make fixing stuff easier later.

**Comment by mdoube** [comment]
>  I'll try something and send you a `imagej-ops-SNAPSHOT`

That did it. Tests all passing now. Will ignore those messages while we wait for the next `imagej-ops`.

**Pull request merged**
