### PR TITLE
Address issue #219 and add little fixes

### PR DESCRIPTION
**Pull request by rimadoma**
This PR fixes issue #219, and fixes other small, mostly stylistic things in EllipsoidFactorWrapper

### CODE REVIEW

**Comment by rimadoma** [comment]
@alessandrofelder Are the conversions in `EllipsoidFactorWrapper` on line 295 necessary?

**Comment by alessandrofelder** [comment]
Some of the images that are divided there consist of integers, so ensuring a float division is important - so I think at least one of the conversions is needed, maybe not both - but don't have time to test that right now

**Comment by mdoube** [comment]
> This PR fixes issue #219, and fixes other small, mostly stylistic things in EllipsoidFactorWrapper

Please check performance implications of the changes and report them (just run before the commits and after the commits on the same image with the same settings and copy paste the stdout output here). We've found that EF is particularly sensitive to small changes.

**Comment by rimadoma** [comment]
```
Old
[INFO] Found 71 ellipsoids in 5734 ms
[INFO] Found maximal ellipsoids in 116 ms

New
[INFO] Found 72 ellipsoids in 5829 ms
[INFO] Found maximal ellipsoids in 192 ms
```

NB These values change a lot from run to run for both old and new

**Comment by alessandrofelder** [comment]
In terms of speed, newer version is slightly faster than current master for me 👍

**Comment by mdoube** [comment]
> In terms of speed, newer version is slightly faster than current master for me +1

We must do this on every PR.

**Comment by rimadoma** [comment]
@alessandrofelder Fixed now. I dropped the "avoid raw types" commits for now.

**Comment by alessandrofelder** [comment]
I am happy with this now :)

**Pull request merged**
