### PR TITLE
Fix issue #195

### PR DESCRIPTION
**Pull request by rimadoma**
This PR fixes issue #195.

In addition it
* Makes the constructor `Orienteer()` `public` again so that the plugin can be run.
* Makes sure that `Orienteer` only calls `UsageReporter` when it's launched as a plugin (and calls it once per run)

@mdoube Since you understand these plugins much better, would you mind checking that they work correctly?

### CODE REVIEW

**Comment by rimadoma** [comment]
I was just trying to fix the bug. I'll have another go, but this behaviour is not my fault. To code is _as is_ from BoneJ1. I was trying to explain why mixing up the constructor and the plugin entry point causes this.

**Comment by mdoube** [comment]
> I was just trying to fix the bug. I'll have another go, but this behaviour is not my fault. To code is _as is_ from BoneJ1. I was trying to explain why mixing up the constructor and the plugin entry point causes this.

Truly weird. Let me take a closer look.

**Comment by rimadoma** [comment]
The refactoring in f890a35 is wrong. I only realised after creating the PR last night. Please start investigation from commit https://github.com/bonej-org/BoneJ2/pull/206/commits/cf3c9486a851a4e760a7d35fab06c14885a68b18

**Comment by rimadoma** [comment]
I think what happens is that when `SliceGeometry` calls `Orienteer.getInstance()` that causes the class to be loaded, which causes it's `private static final Orienteer = new Orienteer()` to initialise, which is the source of the problems. Maybe this can solved by simply removing that init.

**Comment by rimadoma** [comment]
OK, so it was my fault. I had changed line 91 to `private static Orienteer instance = new Orienteer()`; which caused this whole malarkey. At the time I probably thought `getInstance()` shouldn't return `null`, but that was wrong.

I'm hopeful the plugins work now.

**Comment by rimadoma** [comment]
This should solve #159 too

**Comment by mdoube** [comment]
Much better. A couple of remaining problems.

1. Dialog should grey out use Orientation if there is no Orientation window available
2. More severe: `ConcurrentModificationException` when closing image window with Orientation attached:
I think it may be due to the replacement of `Hashtable` with `HashMap`. `Hashtable` is similar to `HashMap` only synchronised. Performance is not super important, but concurrency and synchronisation are for this application.
```
Exception in thread "AWT-EventQueue-0" java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
	at org.bonej.plugins.Orienteer.checkHash(Orienteer.java:383)
	at org.bonej.plugins.Orienteer.update(Orienteer.java:525)
	at org.bonej.plugins.Orienteer.windowActivated(Orienteer.java:332)
	at java.awt.AWTEventMulticaster.windowActivated(AWTEventMulticaster.java:389)
	at java.awt.Window.processWindowEvent(Window.java:2066)
	at java.awt.Window.processEvent(Window.java:2013)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1024)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:516)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.SentEvent.dispatch(SentEvent.java:70)
	at java.awt.DefaultKeyboardFocusManager$DefaultKeyboardFocusManagerSentEvent.dispatch(DefaultKeyboardFocusManager.java:239)
	at java.awt.DefaultKeyboardFocusManager.sendMessage(DefaultKeyboardFocusManager.java:266)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:388)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.SequencedEvent.dispatch(SequencedEvent.java:128)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by rimadoma** [comment]
> I think it may be due to the replacement of Hashtable with HashMap

Yup. Fixed in 1fda758. If I only knew why I thought it was a good idea to change that...

**Comment by rimadoma** [comment]
> Dialog should grey out use Orientation if there is no Orientation window available

Fixed in 2ed8252. Problem was that the option was greyed out in the dialog callback, i.e. the option greyed out if I first touched something else in the dialog. Was this something that worked in BoneJ1?

**Comment by mdoube** [comment]
This all looks promising, but I am having trouble testing:
image
This is after checking out this `refactor-orienteering` branch, building into my Fiji dev directory, and running _Plugins>BoneJ>Analyse>Orientation_

**Comment by mdoube** [comment]
>  the option greyed out if I first touched something else in the dialog. Was this something that worked in BoneJ1?

This is how it 'worked', yes, it should have just been greyed out to begin with. So this fixes a quirk.

**Comment by mdoube** [comment]
> I am having trouble testing:

Testing OK on my workstation in the office: something funky with my laptop.

**Comment by mdoube** [comment]
@rimadoma please check the little commit I made, merge master back in, rebase the merge commit away and resubmit / force push this PR. All looking grand now.

**Comment by rimadoma** [comment]
@mdoube Done. When you merge this PR (I can't), please close the related issues.

If there's been a rebase on the remote branch, and there's nothing on the local branch you want to keep, you can do
```
git checkout branch
git reset --hard origin branch
```
Which avoids merging.

**Pull request merged**
