### PR TITLE
Fix issue #235

### PR DESCRIPTION
**Pull request by rimadoma**
Problem was that macro recording recorded the call to Skeletonize within EF. When _seedOnTopologyPreserving = false_ recording worked fine.

### CODE REVIEW

**Comment by rimadoma** [comment]
@mdoube I haven't figured out yet how to disable the `selectWindow("foo")` lines that result from the output images of EF

**Comment by rimadoma** [comment]
@mdoube Other commands such as ITA might require a similar fix, but let's do them in a separate PR so that this one can go out ASAP

**Comment by mdoube** [comment]
> how to disable the `selectWindow("foo")` lines that result from the output images of EF

These should never really be turned into full images in userland - they have to stay headless. In IJ1 that was achieved by making an `ImagePlus` then calling `.show()` on it for display. Or not even making an `ImagePlus` and leaving the pixel data as an `ImageStack` or raw arrays.

**Comment by rimadoma** [comment]
> These should never really be turned into full images in userland - they have to stay headless. In IJ1 that was achieved by making an ImagePlus then calling .show() on it for display.

I'm wondering if the images need to be output parameters at all. We could just have
```
List<ImgPlus> resultImages = doStuff();
if (!IJ1Helper.isMacro()) {
    resultImages.forEach(o -> uiService::show)
}
```
Then if you wanted to do further stuff to the images, you could still grab them in a macro with selectWindow("Seed points"). Anyhow, I recommend asking the forum about macros and commands.

@alessandrofelder Would Python scripting EF still work if the images were not output parameters?

**Comment by rimadoma** [comment]
> The skeletonisation result flashes up and is then hidden: it should never reach userland.

This too happens because EF runs `SkeletoniseWrapper` through `CommandService`. I can fix both this, and the macro recording bug my having EFWrapper just call a method in `Skeletonize_`

**Comment by rimadoma** [comment]
@alessandrofelder `EllipsoidOptimisationStrategyTest.testMinimumSemiAxisFilter` failed when Michael's merge commit launched the Travis build. When I ran it again manually the test passed. Can this test fail randomly?

**Comment by alessandrofelder** [comment]
🤔 unfortunately don't have time to test your very good questions in detail now, but I hope to find an answer in the next 2 days.

> Would Python scripting EF still work if the images were not output parameters?

Not out of the box the way I am using it, see [Line 88 here](https://github.com/alessandrofelder/EF-helper-scripts/blob/8fa10e49e651e665550b80a7b901d6b01c607983/Python/generate-EF-for-test-images.py#L88), where I reference the output by its variable name in Java. It may be possible to access non-output variables... I don't know. What would you make it instead of an output variable?

**Comment by rimadoma** [comment]
> What would you make it instead of an output variable?

@alessandrofelder Just images I explicitly display if e.g. a macro is not running. I was wondering if in Python scripts you could grab hold of open image windows like in macros / Java? Just something I'm throwing out there, but maybe the forums can help on how to control images popping open / how to do things differently depending on whether a macro is running or not.

**Comment by mdoube** [comment]
> This too happens because EF runs `SkeletoniseWrapper` through `CommandService`. I can fix both this, and the macro recording bug my having EFWrapper just call a method in `Skeletonize_`

That would seem like the sensible thing to do where we have more control over the output.

**Pull request merged**
