### PR TITLE
Clean legacy plugins

### PR DESCRIPTION
**Pull request by rimadoma**
* Cleans plugin related code from Legacy _LocalThickness_ and _Connecitivy_. Leaves only the methods still needed by `ParticleAnalyser` and `SliceGeometry`
* Deletes `RoiMan` which was unused
* Moves single use methods from `StackStats` and `TestDataMaker` and deletes the emtpy classes

### CODE REVIEW

**Comment by mdoube** [comment]
What are the performance implications for these changes?

**Comment by rimadoma** [comment]
Sorry, forgot about legacy Connectivity. being in `plugins.config` I'll remove `@Deprecated` annotation from the class, so I won't make the same mistake again.

**Comment by rimadoma** [comment]
Re: Connectivity BoneJ2 is now using a version of `imagej-ops` that includes your optimised connectivity ops. Is the modern version still slower?

**Comment by mdoube** [comment]
> Re: Connectivity BoneJ2 is now using a version of `imagej-ops` that includes your optimised connectivity ops. Is the modern version still slower?

Yes. On my machine a few times slower. On [emu.tif](http://bonej.org/images/emu.tif) run this macro:
```
run("Purify", "labelling=Mapped chunk=4");

for (i = 0; i < 10; i++){
start = getTime();
run("Connectivity");
end = getTime();
print("Connectivity (Legacy) took "+(end - start)+" ms");

start = getTime();
run("Connectivity (Modern)", "inputimage=net.imagej.ImgPlus@f4c25af");
end = getTime();
print("Connectivity (Modern) took "+(end - start)+" ms");
}
```
I get:
```
Connectivity (Legacy) took 128 ms
Connectivity (Modern) took 455 ms
Connectivity (Legacy) took 111 ms
Connectivity (Modern) took 393 ms
Connectivity (Legacy) took 103 ms
Connectivity (Modern) took 372 ms
Connectivity (Legacy) took 154 ms
Connectivity (Modern) took 356 ms
Connectivity (Legacy) took 121 ms
Connectivity (Modern) took 384 ms
Connectivity (Legacy) took 121 ms
Connectivity (Modern) took 372 ms
Connectivity (Legacy) took 118 ms
Connectivity (Modern) took 362 ms
Connectivity (Legacy) took 113 ms
Connectivity (Modern) took 379 ms
Connectivity (Legacy) took 121 ms
Connectivity (Modern) took 365 ms
Connectivity (Legacy) took 106 ms
Connectivity (Modern) took 364 ms
```

**Comment by rimadoma** [comment]
Shouldn't have "optimised" by creating only one instance. I already had this right...

**Comment by mdoube** [comment]
Looking good, no more exceptions here.

**Pull request merged**
