### PR TITLE
Remove broken ROI handling behaviour

### PR DESCRIPTION
**Pull request by mdoube**
Modern Thickness was cropping to irregular ROIs rather than masking, which is quite different behaviour than BoneJ1, which might confuse users and lead to wrong results. A rethink of ROI handling is required - hopefully there is a better approach to ROIs in ImageJ2 by now. This code excision is a first step in addressing #164

### CODE REVIEW

**Comment by mdoube** [comment]
@rimadoma there are possibly other files to edit such as instructions for testing or documentation - please point me in the right direction.

**Comment by rimadoma** [comment]
@mdoube There's the technical documentation at the wiki in the repository here and then user documentation at imagej.Net

**Comment by mdoube** [comment]
OK @rimadoma docs updated (very good docs BTW - thanks!)

**Comment by ctrueden** [comment]
> Would be good to know how ROIs work in IJ2, but haven't found the time to figure it out yet.

https://imagej.net/ROIs, if you didn't already see it, @alessandrofelder.

We still need to make some Jupyter notebooks illustrating the latest ImgLib2 ROI API.

**Pull request merged**
